name: "lint"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Run linters
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: 'Use Node.js 20.6'
        uses: actions/setup-node@v3
        with:
          node-version: '20.6'

      - name: 'Use pnpm 8'
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: |
            - args: [--frozen-lockfile]

      # Linters
      - run: pnpm run lint

      # Formatters
      - run: pnpm run format
